import FacebookIcon from '@mui/icons-material/Facebook';
import TwitterIcon from '@mui/icons-material/Twitter';
import InstagramIcon from '@mui/icons-material/Instagram';

// Classes data
export const dataClasses = [
    {
        id: "1",
        img: "../images/classes-1.jpg",
        heading: "Art & Drawing",
        user: "../images/user.jpg",
        name: "John Doe",
        Worker: "Teacher",
        rupees: "14,500",
        age: "Age:",
        ageYear: "3 - 5 years",
        time: "Time:",
        timeClock: "9 - 10am",
        capacity: "Capacity:",
        capacityKids: "30 kids",
    },
    {
        id: "2",
        img: "../images/classes-2.jpg",
        heading: "Color Management",
        user: "../images/user.jpg",
        name: "John Doe",
        Worker: "Teacher",
        rupees: "14,500",
        age: "Age:",
        ageYear: "3 - 5 years",
        time: "Time:",
        timeClock: "9 - 10am",
        capacity: "Capacity:",
        capacityKids: "30 kids",
    },
    {
        id: "3",
        img: "../images/classes-3.jpg",
        heading: "Athletic & Dance",
        user: "../images/user.jpg",
        name: "John Doe",
        Worker: "Teacher",
        rupees: "14,500",
        age: "Age:",
        ageYear: "3 - 5 years",
        time: "Time:",
        timeClock: "9 - 10am",
        capacity: "Capacity:",
        capacityKids: "30 kids",
    },
    {
        id: "4",
        img: "../images/classes-4.jpg",
        heading: "Language & Speaking",
        user: "../images/user.jpg",
        name: "John Doe",
        Worker: "Teacher",
        rupees: "14,500",
        age: "Age:",
        ageYear: "3 - 5 years",
        time: "Time:",
        timeClock: "9 - 10am",
        capacity: "Capacity:",
        capacityKids: "30 kids",
    },
    {
        id: "5",
        img: "../images/classes-5.jpg",
        heading: "Religion & History",
        user: "../images/user.jpg",
        name: "John Doe",
        Worker: "Teacher",
        rupees: "14,500",
        age: "Age:",
        ageYear: "3 - 5 years",
        time: "Time:",
        timeClock: "9 - 10am",
        capacity: "Capacity:",
        capacityKids: "30 kids",
    },
    {
        id: "6",
        img: "../images/classes-2.jpg",
        heading: "General Knowledge",
        user: "../images/user.jpg",
        name: "John Doe",
        Worker: "Teacher",
        rupees: "14,500",
        age: "Age:",
        ageYear: "3 - 5 years",
        time: "Time:",
        timeClock: "9 - 10am",
        capacity: "Capacity:",
        capacityKids: "30 kids",
    },
]

export const popularData = [
    {
        id: "1",
        avatarImg: "../images/team-1.jpg",
        titleName: "Kapeha",
        designation: "Software Engineering",
        fb: <FacebookIcon />,
        twitter: <TwitterIcon />,
        ig: <InstagramIcon />
    },
    {
        id: "2",
        avatarImg: "../images/team-2.jpg",
        titleName: "John Doe",
        designation: "Full Stack Development",
        fb: <FacebookIcon />,
        twitter: <TwitterIcon />,
        ig: <InstagramIcon />
    },
    {
        id: "3",
        avatarImg: "../images/team-3.jpg",
        titleName: "Bhavani",
        designation: "UX Desginer",
        fb: <FacebookIcon />,
        twitter: <TwitterIcon />,
        ig: <InstagramIcon />
    },
]